import React from "react";

interface NarrativeProps {
  title?: string;
  source?: string;
}

const Narrative: React.FC<NarrativeProps> = ({ 
  title = "AI Insights", 
  source = "insights_text" 
}) => {
  // Mock AI-generated insights based on typical dashboard data
  const mockInsights = [
    "Strong growth observed in Asian markets with Singapore leading at 22% YoY increase.",
    "Employee distribution shows healthy concentration in major financial hubs with optimal branch sizes.",
    "Health scores indicate robust operational efficiency across all regions, particularly in European branches.",
    "Recommendation: Consider expanding in Southeast Asia given current growth trajectory and market potential."
  ];

  return (
    <div className="bg-[#1E293B] rounded-xl p-6 border border-[#164E63] shadow-[0_10px_30px_rgba(0,0,0,0.45)]">
      <h3 className="text-lg font-semibold text-[#F1F5F9] mb-4">{title}</h3>
      
      <div className="space-y-3">
        {mockInsights.map((insight, index) => (
          <div
            key={index}
            className="p-4 bg-[#111827] rounded-lg border border-[#164E63]/50"
          >
            <div className="flex items-start space-x-3">
              <div className="w-6 h-6 bg-[#06B6D4] rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-xs font-bold text-[#0F172A]">AI</span>
              </div>
              <p className="text-sm text-[#F1F5F9] leading-relaxed">{insight}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-4 pt-4 border-t border-[#164E63]/50">
        <div className="flex items-center justify-between text-xs text-[#94A3B8]">
          <span>Generated by MapMyWork AI</span>
          <span>Updated: Just now</span>
        </div>
      </div>
    </div>
  );
};

export default Narrative;
